name: Deploy
on:
  push:
    branches: [ master, add-deploy ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.SERVER_IP }} "
          cd ~/vtb25 &&
          git checkout master &&
          git pull origin master &&
          cd frontend &&
          npm install &&
          npm run build &&
          pm2 reload vtb25 || pm2 start ecosystem.config.cjs
        "
