name: Deploy
on:
  push:
    branches: [ add-deploy, master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to server
      run: |
        ssh -l ${{ secrets.USER }} ${{ secrets.SERVER_IP }} "
          cd ~/vtb25 &&
          git checkout master &&
          git pull origin master &&
          cd frontend &&
          npm install &&
          npm run build &&
          pm2 reload vtb25 || pm2 start ecosystem.config.cjs
        "
